sudo: false
language: node_js
node_js:
- '4'
env:
  global:
  - secure: wXlv2AeObwdJPRr/fnSd8LkFnYNfPkOGzAkYXnoLKfzQr5t35xk7OSHHJAWtK11vy5F+ob4Z52tsIkSrLBrb6zAskH3zJIA/dwk9EeZ2y2OdDSWUyf9tderUbd+SHEOmpUo/wBelKo/PLkpnHlaDUtzHEWpy3Rrfz9A3W2FVeWAM/o/MnljQFYxkc2JTWt9eFOqpB1z3Z5m4OrWA2dgren5aCCyZLZgbqP4TIv/Esod1Z377HbV7D0cdzE4Ptm96RiyDbiITQcyhSoNn9VN5BvrX2Oz+G9Lymz8+vV1cxde0Y3uyrAXq7JhrFqDbjeBeafBf8gaCD5RTBEalLux+iLCeMTmOQEhzxIJpnndv31sH9KbpiFG5h9IwH/8Snt+U0C42o0M3lrMMj/eH/+mmcaM1YwMuGytk4v2SZ+8d9Q5M0uK+knGLm16HCpkwCfmFfCmFteLBVlRkqikWtGYEYcVCROA/i0yVVJny7DFT4jaFjG99weTTDBQ5lgeMiSfbVDjtpy2Lt+HOFcDbOYkwCsaJLpDXCo69GdjeNrHvT9vBGM3Pp6krOrTLwCtu59DtfYutA9+4STKXyuC9aw2z6Mm6HpKJw6bNKyJegtfm9gzbuiVlu/NKZDuseUjf6K2zsq9Jjs84P+X7oAOHlUSrKYz3iwcJG0zjmXB1oBVnp7I=
after_success:
# update gh-page only for master
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    chmod +x ./resources/scripts/update-gh-pages.sh; "./resources/scripts/update-gh-pages.sh";
  else echo "Not deploying artifacts for $TRAVIS_BRANCH"; fi
